title: Site

tabs:
  # content tab
  content:
    label: Content
    icon: text
    sections:
    fields:
      pages:
        type: pages
        layout: cards

  # Config tab
  config:
    label: Config
    icon: cog
    columns:

      # main
      left:
        width: 1/2
        sections:
        fields:
          instagram:
            type: url
          vimeo:
            type: url
          linktree:
            type: url
      right:
        width: 1/2
        sections:
        fields:
          phone:
            type: tel
          mail:
            type: email
          fondsonore:
            label: Fond sonore
            type: files
            mutliple: false
            query: page.audio
          portfoliopdf:
            label: Portfolio PDF
            type: files
            mutliple: false
            query: page.documents

  translations:
    icon: translate

    fields:
      portfoliobtn:
        label: Portfolio
        type: text
      audiobtn:
        label: Audio
        type: text
      fullscreenbtn:
        label: Fullscreen
        type: text
      loading:
        label: Chargement
        type: text
